<!-- Coordinator Dashboard View -->
<div class="row g-4 mb-4">
    <!-- Stat card 1 -->
    <div class="col-md-4">
        <div class="stat-card p-4 d-flex align-items-center justify-content-between bg-white border rounded-3 shadow-sm">
            <div>
                <h6 class="text-muted small text-uppercase mb-2 font-weight-bold">Pending Student Approvals</h6>
                <h3 class="m-0 fw-bold <?php echo $stats['pending_approvals'] > 0 ? 'text-warning animate-pulse' : 'text-dark'; ?>">
                    <?php echo $stats['pending_approvals']; ?>
                </h3>
            </div>
            <div class="card-icon icon-warning">
                <i class="bi bi-person-fill-exclamation"></i>
            </div>
        </div>
    </div>
    
    <!-- Stat card 2 -->
    <div class="col-md-4">
        <div class="stat-card p-4 d-flex align-items-center justify-content-between bg-white border rounded-3 shadow-sm">
            <div>
                <h6 class="text-muted small text-uppercase mb-2 font-weight-bold">Active Students in Dept</h6>
                <h3 class="m-0 fw-bold text-success"><?php echo $stats['total_students']; ?></h3>
            </div>
            <div class="card-icon icon-success animate-hover">
                <i class="bi bi-people-fill"></i>
            </div>
        </div>
    </div>

    <!-- Stat card 3 -->
    <div class="col-md-4">
        <div class="stat-card p-4 d-flex align-items-center justify-content-between bg-white border rounded-3 shadow-sm">
            <div>
                <h6 class="text-muted small text-uppercase mb-2 font-weight-bold">Notices Generated</h6>
                <h3 class="m-0 fw-bold text-primary"><?php echo $stats['total_notices']; ?></h3>
            </div>
            <div class="card-icon icon-primary">
                <i class="bi bi-megaphone-fill"></i>
            </div>
        </div>
    </div>
</div>

<div class="row g-4">
    <div class="col-lg-8">
        <div class="card border-0 shadow-sm rounded-3 p-4 bg-white mb-4">
            <div class="d-flex align-items-center justify-content-between mb-4 pb-2 border-bottom">
                <div>
                    <h5 class="fw-bold text-dark m-0">Recent Notices Generated</h5>
                    <p class="text-muted m-0 small">Broadcasting timeline changes and instructions for <?php echo htmlspecialchars($department); ?></p>
                </div>
                <a href="<?php echo dirname($_SERVER['SCRIPT_NAME']) === '/' || dirname($_SERVER['SCRIPT_NAME']) === '\\' ? '' : dirname($_SERVER['SCRIPT_NAME']); ?>/coordinator/notice" class="btn btn-sm btn-outline-primary rounded-pill px-3">Create Notice</a>
            </div>

            <div class="table-responsive">
                <table class="table table-hover align-middle border-0 m-0">
                    <thead>
                        <tr>
                            <th>Ref No.</th>
                            <th>Subject</th>
                            <th>Date</th>
                            <th>Target</th>
                            <th class="text-end">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($recentNotices as $n): ?>
                        <tr>
                            <td class="font-monospace fw-bold text-secondary"><?php echo htmlspecialchars($n['ref_no'] ?? 'N/A'); ?></td>
                            <td>
                                <div class="fw-semibold text-dark text-wrap" style="max-width: 250px;">
                                    <?php echo htmlspecialchars($n['subject']); ?>
                                </div>
                            </td>
                            <td><?php echo date('M d, Y', strtotime($n['notice_date'])); ?></td>
                            <td>
                                <span class="badge rounded-pill bg-light text-dark border px-2.5 py-1 text-uppercase" style="font-size: 0.7rem;">
                                    <?php echo htmlspecialchars($n['target_audience']); ?>
                                </span>
                            </td>
                            <td class="text-end">
                                <a href="<?php echo dirname($_SERVER['SCRIPT_NAME']) === '/' || dirname($_SERVER['SCRIPT_NAME']) === '\\' ? '' : dirname($_SERVER['SCRIPT_NAME']); ?>/notice/view?id=<?php echo $n['id']; ?>" target="_blank" class="btn btn-sm btn-outline-primary rounded-pill px-3">View Letter</a>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                        <?php if(empty($recentNotices)): ?>
                            <tr>
                                <td colspan="5" class="text-center text-muted py-4">No notices generated by you yet.</td>
                            </tr>
                        <?php endif; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="col-lg-4">
        <div class="card border-0 shadow-sm rounded-3 p-4 bg-white text-center">
            <h5 class="fw-bold text-dark mb-3">Verification Quick Link</h5>
            <p class="text-muted small">You have <strong class="text-warning"><?php echo $stats['pending_approvals']; ?></strong> pending registrations waiting for verification in your department.</p>
            <a href="<?php echo dirname($_SERVER['SCRIPT_NAME']) === '/' || dirname($_SERVER['SCRIPT_NAME']) === '\\' ? '' : dirname($_SERVER['SCRIPT_NAME']); ?>/coordinator/users" class="btn btn-primary w-100 rounded-pill py-2.5 mt-2 fw-semibold">
                <i class="bi bi-shield-check me-2"></i> Verify Student Registry
            </a>
        </div>
    </div>
</div>
